// src/surahNames.js
const surahNames = [
    "Al-Fatiha",           // 001
    "Al-Baqarah",          // 002
    "Aal-E-Imran",         // 003
    "An-Nisa'",            // 004
    "Al-Ma'idah",          // 005
    "Al-An'am",            // 006
    "Al-A'raf",            // 007
    "Al-Anfal",            // 008
    "At-Tawbah",           // 009
    "Yunus",               // 010
    "Hud",                 // 011
    "Yusuf",               // 012
    "Ar-Ra'd",             // 013
    "Ibrahim",             // 014
    "Al-Hijr",             // 015
    "An-Nahl",             // 016
    "Al-Isra",             // 017
    "Al-Kahf",             // 018
    "Maryam",              // 019
    "Ta-Ha",               // 020
    "Al-Anbiya",           // 021
    "Al-Hajj",             // 022
    "Al-Mu'minun",         // 023
    "An-Nur",              // 024
    "Al-Furqan",           // 025
    "Ash-Shu'ara",         // 026
    "An-Naml",             // 027
    "Al-Qasas",            // 028
    "Al-Ankabut",          // 029
    "Ar-Rum",              // 030
    "Luqman",              // 031
    "As-Sajda",            // 032
    "Al-Ahzab",            // 033
    "Saba",                // 034
    "Fatir",               // 035
    "Ya-Sin",              // 036
    "As-Saffat",           // 037
    "Sad",                 // 038
    "Az-Zumar",            // 039
    "Ghafir",              // 040
    "Fussilat",            // 041
    "Ash-Shura",           // 042
    "Az-Zukhruf",          // 043
    "Ad-Dukhan",           // 044
    "Al-Jathiya",          // 045
    "Al-Ahqaf",            // 046
    "Muhammad",            // 047
    "Al-Fath",             // 048
    "Al-Hujurat",          // 049
    "Qaf",                 // 050
    "Adh-Dhariyat",        // 051
    "At-Tur",              // 052
    "An-Najm",             // 053
    "Al-Qamar",            // 054
    "Ar-Rahman",           // 055
    "Al-Waqia",            // 056
    "Al-Hadid",            // 057
    "Al-Mujadila",         // 058
    "Al-Hashr",            // 059
    "Al-Mumtahina",        // 060
    "As-Saff",             // 061
    "Al-Jumua",            // 062
    "Al-Munafiqun",        // 063
    "At-Taghabun",         // 064
    "At-Talaq",            // 065
    "At-Tahrim",           // 066
    "Al-Mulk",             // 067
    "Al-Qalam",            // 068
    "Al-Haqqah",           // 069
    "Al-Ma'arij",          // 070
    "Nuh",                 // 071
    "Al-Jinn",             // 072
    "Al-Muzzammil",        // 073
    "Al-Muddaththir",      // 074
    "Al-Qiyama",           // 075
    "Al-Insan",            // 076
    "Al-Mursalat",         // 077
    "An-Naba",             // 078
    "An-Nazi'at",          // 079
    "Abasa",               // 080
    "At-Takwir",           // 081
    "Al-Infitar",          // 082
    "Al-Mutaffifin",       // 083
    "Al-Inshiqaq",         // 084
    "Al-Buruj",            // 085
    "At-Tariq",            // 086
    "Al-A'la",             // 087
    "Al-Ghashiyah",        // 088
    "Al-Fajr",             // 089
    "Al-Balad",            // 090
    "Ash-Shams",           // 091
    "Al-Layl",             // 092
    "Ad-Duhaa",            // 093
    "Ash-Sharh",           // 094
    "At-Tin",              // 095
    "Al-Alaq",             // 096
    "Al-Qadr",             // 097
    "Al-Bayyina",          // 098
    "Az-Zalzalah",         // 099
    "Al-Adiyat",           // 100
    "Al-Qaria",            // 101
    "At-Takathur",         // 102
    "Al-Asr",              // 103
    "Al-Humazah",          // 104
    "Al-Fil",              // 105
    "Quraish",             // 106
    "Al-Ma'un",            // 107
    "Al-Kawthar",          // 108
    "Al-Kafirun",          // 109
    "An-Nasr",             // 110
    "Al-Masad",            // 111
    "Al-Ikhlas",           // 112
    "Al-Falaq",            // 113
    "An-Nas"               // 114
  ];
  
  export default surahNames;
  